server:
  port: 8079
  servlet:
    session:
      cookie:
        name: BFFSESSIONID
        http-only: true
        same-site: lax

spring:
  application:
    name: spring-member-bff-service

  session:
    store-type: redis
    data:
      redis:
        namespace: spring:session:bff

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.memberbff: debug
