spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          member-bff:
            provider: member-auth-server
            client-id: ${BFF_CLIENT_ID}
            client-secret: ${BFF_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${BFF_OAUTH2_REDIRECT_URI}
            scope:
              - openid
              - profile
        provider:
          member-auth-server:
            authorization-uri: ${BFF_OAUTH2_AUTHORIZATION_URI}
            token-uri: ${BFF_OAUTH2_TOKEN_URI}
            user-info-uri: ${BFF_OAUTH2_USERINFO_URI}
            jwk-set-uri: ${BFF_OAUTH2_JWK_SET_URI}
            user-name-attribute: sub

bff:
  frontend:
    redirect-uri: ${BFF_FRONTEND_REDIRECT_URI}

  oauth2:
    end-session-uri: ${BFF_OAUTH2_END_SESSION_URI}
    logout-uri: ${BFF_OAUTH2_LOGOUT_URI}

  api:
    user-api-base-url: ${BFF_API_USER_API_BASE_URL}
    user-internal-base-url: ${BFF_API_USER_INTERNAL_BASE_URL}
    community-api-base-url: ${BFF_API_COMMUNITY_API_BASE_URL}
    stock-api-base-url: ${BFF_API_STOCK_API_BASE_URL}

logging:
  level:
    com.springmsa.memberbff: info
