CREATE TABLE chat_rooms (
    chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_chat_rooms_room_id UNIQUE (room_id)
);

CREATE TABLE chat_messages (
    chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_user_id BIGINT,
    sender_login_id VARCHAR(100),
    sender_name VARCHAR(100),
    content VARCHAR(1000) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_messages_room
        FOREIGN KEY (chat_room_id)
        REFERENCES chat_rooms (chat_room_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_chat_messages_room_message
    ON chat_messages (chat_room_id, chat_message_id);

CREATE INDEX idx_chat_messages_room_sent_at
    ON chat_messages (chat_room_id, sent_at);
