CREATE TABLE processed_kafka_events (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(150) NOT NULL,
    consumer_group VARCHAR(150) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE member_notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    recipient_sub VARCHAR(100) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_member_notifications_event UNIQUE (event_id)
);

CREATE INDEX idx_member_notifications_recipient
    ON member_notifications (recipient_sub, created_at DESC);
